apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deploy
  labels:
    name: my-app-deploy
    app: demo-my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-app-pod
      app: demo-my-app
  template:
    metadata:
      name: my-app-pod
      labels:
        name: my-app-pod
        app: demo-my-app
    spec:
      containers:
        - name: my-app
          image: abhishekvunet/my_app:v3.0
          ports:
            - containerPort: 8000
          env:
            - name : SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: my-app-secret
                  key: SECRET_KEY