apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels: 
    name: my-app-service
    app: demo-my-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30009
  selector:
    name: my-app-pod
    app: demo-my-app
    